### ISSUE TITLE
Latest 10.15.6 updates causes screen wake failure from sleep.

### ISSUE THREAD

**Issue by jt1900jt** [doubleyoustew/Razer-Blade-15#2]
the screen will not come back from black without closing the lid and reopening the laptop. Also the battery drain at a excessive rate after this without a restart.

**Comment by doubleyoustew** [comment]
I'm still on 10.14.6 so I can't test it. Sounds like your dGPU patch isn't working though. Did you use my EFI? What model do you have? Upload your EFI folder and I can take a look.

**Comment by jt1900jt** [comment]
[EFI.zip](https://github.com/doubleyoustew/Razer-Blade-15/files/5191599/EFI.zip)


Here is my EFI. I used your EFI as my base. I updated to OC 0.6.1 today. 


Here is the crash log:

Sleep Wake failure in EFI

Failure code:: 0xffffffff 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2020-09-09 11:22:51 -0700
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   29

Data Source:      Stackshots
Shared Cache:     0xa5cc000 EEC4AE11-62C9-3170-9B83-DEBA72179AEB

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        keepsyms=1 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 27s



Process:          swd [360]
Architecture:     x86_64
Footprint:        428 KB
Start time:       2020-09-09 11:22:51 -0700
End time:         2020-09-09 11:22:51 -0700
Num samples:      1 (1)

  Thread 0xbb2    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 109769) [0x7fff715eccc9] 1
    1  ??? [0x107565454] 1
      1  ??? [0x1075651dd] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135862) [0x7fff7174e2b6] 1
         *1  ??? [0xffffff80002c1206] 1
           *1  ??? [0xffffff8000984c37] 1
             *1  ??? [0xffffff800089d7c1] 1
               *1  ??? [0xffffff80002e49e7] (running) 1

  Binary Images:
        0x7fff715d2000 -     0x7fff71608fff  libdyld.dylib (750.6)               <789A18C2-8AC7-3C88-813D-CD674376585D>  /usr/lib/system/libdyld.dylib
        0x7fff7172d000 -     0x7fff71759fff  libsystem_kernel.dylib (6153.141.1) <2B6311E6-6240-3EF7-8C87-475B66F7452C>  /usr/lib/system/libsystem_kernel.dylib
Model: MacBookPro15,3, BootROM 1554.40.9.0.0, 6 processors, 6-Core Intel Core i7, 2.2 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, Samsung, M471A1K43CB1-CTD
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, Samsung, M471A1K43CB1-CTD
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x19), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.1)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
USB Device: USB 3.1 Bus
USB Device: Razer Blade
USB Device: Integrated Camera
USB Device: BCM20702A0
USB Device: USB 3.1 Bus
Thunderbolt Bus:

**Comment by doubleyoustew** [comment]
So what's the problem exactly? Does it kernel panic after waking up from sleep and restart? Your first comment looks like you can use your laptop after sleep, your second one looks like a panic report after a restart.

Maybe it's the same bug mentioned here:
https://www.reddit.com/r/hackintosh/comments/fxt6hl/sleep_wake_failure_in_efi/

Which model do you have?

**Comment by jt1900jt** [comment]
I get a kernel panic when waking up from sleep and the computer has restarted. That is the panic report. It looks like its the same issue as that post but I don't see any option for disabling serial port in my bios. any suggestions?

**Comment by doubleyoustew** [comment]
Sorry mate, no idea at the moment. I don't experience the bug myself and from what I've read it might just be a Catalina bug. Things that you could try:

- Disable Power Nap
- sudo pmset -a hibernatemode 0
- sudo pmset -a standby 0

That last one seems to have helped Macbook owners who had the same problem. The first two are mandatory for this hackintosh anyways and I should add it to the readme. Hope it helps!
